

function init(self)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and message.other_id == hash("/fairy_player") then
		msg.post("/last_door", hash("open"))
		msg.post("/laser_beam_4", hash("beam_4"))
	end
end