function init(self)
	go.property("deleting", false)
	go.set_position([-800, -800])
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("beam_4") then

	end
	if message_id == hash("kill") then
		if self.deleting == false then
			self.deleting = true
			go.delete()
		end
	end
end