function init(self)
	go.property("deleting", false)
	go.set(".", "position.x", -800)
	go.set(".", "position.y", -800)
end

function final(self)
	msg.post(hash("/laser_beam_2"), hash("beam_2"))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("beam_1") then
		go.set(".", "position.x", 0)
		go.set(".", "position.y", 0)
	end
	if message_id == hash("kill") then
		if self.deleting == false then
			self.deleting = true
			go.delete()
		end
	end
end