function init(self)
	go.property("deleting", false)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == open then
		if self.deleting == false then
			self.deleting = true
			go.delete()
			msg.post(laser_beam_1, step_3)
		end
	end
end